### PR TITLE
week-6 TapPay

### PR DESCRIPTION
**Pull request by pcchou1997**
Dear Teacher Ponpon,

My name is 周品甄, I have finished the homework this week and deployed it on the AWS EC2 service.
Below are my test urls:

・http://15.152.11.87:3000/

Please help to confirm if any serious problem exists, thanks to teacher Ponpon!

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
Don't show prime key in alert dialog when ordering.

**Comment by pcchou1997** [comment]
Dear Teacher Ponpon,

My name is 周品甄, I have revised the issues you mentioned, including:
(1) not show the prime key in alert dialog when clicking order button

Below are my test url:
・http://15.152.11.87:3000/

Please help to confirm the result be correct or not, thanks to teacher Ponpon!

**Comment by cwpeng** [comment]
Should I review this?

**Comment by pcchou1997** [comment]
Dear Teacher Ponpon,

I'm sorry to bother teacher for this mistake. What I mean to say was that I revised the mistake.
If my words or actions offend teacher, please let me know.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
