### PR TITLE
update app.py port number

### PR DESCRIPTION
**Pull request by pcchou1997**
老師好，我是周品甄，再麻煩老師撥空確認，謝謝！

### CODE REVIEW

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should setup protection rule for `main` branch.

**Comment by pcchou1997** [comment]
老師好，我是周品甄，
我已將建立的「分支保護規則」重新命名為main、並將相關規則選項打勾，
再請確認，謝謝老師！

**Comment by cwpeng** [comment]
Re-request review from reviewers section in the right side of this page if you fix issue.

**Comment by pcchou1997** [comment]
I send re-request, thanks teacher Ponpon!

**Review by cwpeng — APPROVED** [review]
OK. Remember to merge pull request after review approval.

**Pull request merged**
